version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/repo
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: rails-demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: rails-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: mv config/database.yml.ci config/database.yml
      - run: gem install cucumber-rails
      - run: cucumber --init
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel

      - run:
          name: run tests
          command: |
            bundle exec cucumber
      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
